spring:
  application:
    name: kaiburr-task1
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/kaiburrdb}
      auto-index-creation: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  
  servlet:
    multipart:
      enabled: false

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    dev.adityar.kaiburr: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

app:
  security:
    policy-file: ${POLICY_FILE:config/command-policy.yaml}
  audit:
    log-file: ${AUDIT_LOG:audit.log.jsonl}
